--------------------------------------------------------
--  DDL for Table ADMINNOTICE
--------------------------------------------------------

  CREATE TABLE "BOOK"."ADMINNOTICE" 
   (	"NUM" NUMBER, 
	"WRITER" VARCHAR2(100 BYTE), 
	"TITLE" VARCHAR2(1000 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"REGDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "BOOK"."BOARD" 
   (	"BNO" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(4000 BYTE), 
	"WRITER" VARCHAR2(50 BYTE), 
	"REGDATE" DATE DEFAULT sysdate, 
	"VIEWCNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BOOK_INFO
--------------------------------------------------------

  CREATE TABLE "BOOK"."BOOK_INFO" 
   (	"BOOK" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"PRICE" NUMBER, 
	"AUTHOR" VARCHAR2(100 BYTE), 
	"PUBLISHER" VARCHAR2(100 BYTE), 
	"TYPE" VARCHAR2(100 BYTE), 
	"ISBN" VARCHAR2(100 BYTE), 
	"CATEGORY" VARCHAR2(10 BYTE), 
	"ID" VARCHAR2(100 BYTE), 
	"IMAGE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BRANCH_INFO
--------------------------------------------------------

  CREATE TABLE "BOOK"."BRANCH_INFO" 
   (	"NAME" VARCHAR2(20 BYTE), 
	"ADDRESS1" VARCHAR2(200 BYTE), 
	"ADDRESS2" VARCHAR2(200 BYTE), 
	"PHONE" VARCHAR2(11 BYTE), 
	"MASTER" VARCHAR2(20 BYTE), 
	"EMPCOUNT" NUMBER, 
	"SALES" NUMBER, 
	"TIME" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CART
--------------------------------------------------------

  CREATE TABLE "BOOK"."CART" 
   (	"STATUS" VARCHAR2(50 BYTE), 
	"CARTNO" NUMBER, 
	"ID" VARCHAR2(50 BYTE), 
	"ISBN" VARCHAR2(50 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"IMAGE" VARCHAR2(100 BYTE), 
	"PRICE" NUMBER, 
	"AMOUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "BOOK"."CUSTOMER" 
   (	"ID" VARCHAR2(20 BYTE), 
	"PWD" VARCHAR2(20 BYTE), 
	"CUSTOMERCLASS" VARCHAR2(20 BYTE), 
	"ZIPCODE" VARCHAR2(10 BYTE), 
	"ADDRESS1" VARCHAR2(200 BYTE), 
	"ADDRESS2" VARCHAR2(200 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PHONE" VARCHAR2(11 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CUSTOMERCLASS
--------------------------------------------------------

  CREATE TABLE "BOOK"."CUSTOMERCLASS" 
   (	"NAME" VARCHAR2(100 BYTE), 
	"DISCOUNT" NUMBER, 
	"EXPLAIN" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CUSTOMERNOTICE
--------------------------------------------------------

  CREATE TABLE "BOOK"."CUSTOMERNOTICE" 
   (	"TITLE" VARCHAR2(50 BYTE), 
	"CONTENT" VARCHAR2(3000 BYTE), 
	"REGDATE" DATE, 
	"ARTICLENUMBER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EBOOK_DISTLIST
--------------------------------------------------------

  CREATE TABLE "BOOK"."EBOOK_DISTLIST" 
   (	"ISBN" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"ONO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EBOOK_EXTENDREQLIST
--------------------------------------------------------

  CREATE TABLE "BOOK"."EBOOK_EXTENDREQLIST" 
   (	"ONO" NUMBER, 
	"EXTENDDATE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EBOOK_ORGAN
--------------------------------------------------------

  CREATE TABLE "BOOK"."EBOOK_ORGAN" 
   (	"ONO" NUMBER, 
	"OPWD" VARCHAR2(20 BYTE), 
	"ONAME" VARCHAR2(50 BYTE), 
	"DEADLINE" VARCHAR2(70 BYTE), 
	"TYPE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EBOOK_REQLIST
--------------------------------------------------------

  CREATE TABLE "BOOK"."EBOOK_REQLIST" 
   (	"REQNO" NUMBER, 
	"ISBN" VARCHAR2(50 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"ONO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "BOOK"."EMPLOYEE" 
   (	"EMPNO" NUMBER, 
	"PWD" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"EMPCLASS" VARCHAR2(20 BYTE), 
	"ADDRESS1" VARCHAR2(200 BYTE), 
	"ADDRESS2" VARCHAR2(200 BYTE), 
	"PHONE" VARCHAR2(11 BYTE), 
	"GENDER" VARCHAR2(1 BYTE), 
	"BIRTH" VARCHAR2(6 BYTE), 
	"BRANCH" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEECLASS
--------------------------------------------------------

  CREATE TABLE "BOOK"."EMPLOYEECLASS" 
   (	"NAME" VARCHAR2(20 BYTE), 
	"BASEPAY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GETDELIVERY
--------------------------------------------------------

  CREATE TABLE "BOOK"."GETDELIVERY" 
   (	"ORDERNO" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"ZIPCODE" VARCHAR2(20 BYTE), 
	"ADDRESS1" VARCHAR2(100 BYTE), 
	"ADDRESS2" VARCHAR2(100 BYTE), 
	"ORDERDATE" DATE DEFAULT sysdate, 
	"PHONE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GETDIRECT
--------------------------------------------------------

  CREATE TABLE "BOOK"."GETDIRECT" 
   (	"ORDERNO" NUMBER, 
	"ISBN" VARCHAR2(100 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"QUANTITY" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"BRANCH" VARCHAR2(20 BYTE), 
	"GETDATE" DATE DEFAULT sysdate, 
	"ISPAID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table INVENTORY
--------------------------------------------------------

  CREATE TABLE "BOOK"."INVENTORY" 
   (	"ISBN" VARCHAR2(100 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"QUANTITY" NUMBER, 
	"BRANCH" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NOTICE
--------------------------------------------------------

  CREATE TABLE "BOOK"."NOTICE" 
   (	"TITLE" VARCHAR2(50 BYTE), 
	"CONTENT" VARCHAR2(3000 BYTE), 
	"REGDATE" DATE, 
	"ARTICLENUMBER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDERLIST
--------------------------------------------------------

  CREATE TABLE "BOOK"."ORDERLIST" 
   (	"TITLE" VARCHAR2(200 BYTE), 
	"PUBLISHER" VARCHAR2(50 BYTE), 
	"QUANTITY" NUMBER, 
	"BRANCH" VARCHAR2(20 BYTE), 
	"COST" NUMBER, 
	"O_DATE" VARCHAR2(10 BYTE), 
	"ISBN" VARCHAR2(100 BYTE), 
	"ORDERNUMBER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REPLY
--------------------------------------------------------

  CREATE TABLE "BOOK"."REPLY" 
   (	"RNO" NUMBER, 
	"BNO" NUMBER DEFAULT 0, 
	"REPLYTEXT" VARCHAR2(1000 BYTE), 
	"REPLYER" VARCHAR2(50 BYTE), 
	"REGDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SALARY
--------------------------------------------------------

  CREATE TABLE "BOOK"."SALARY" 
   (	"EMPNO" NUMBER, 
	"BONUS" NUMBER, 
	"PAYMENT" NUMBER, 
	"BANK" VARCHAR2(20 BYTE), 
	"ACCOUNT" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SALELIST
--------------------------------------------------------

  CREATE TABLE "BOOK"."SALELIST" 
   (	"ISBN" VARCHAR2(100 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"DPRICE" NUMBER, 
	"BRANCHNAME" VARCHAR2(20 BYTE), 
	"QUANTITY" NUMBER, 
	"S_DATE" VARCHAR2(100 BYTE), 
	"SALENUMBER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007332
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOK"."SYS_C007332" ON "BOOK"."BOARD" ("BNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "BOOK"."BOARD" ADD PRIMARY KEY ("BNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BOOK"."BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "BOOK"."BOARD" MODIFY ("BNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMERNOTICE
--------------------------------------------------------

  ALTER TABLE "BOOK"."CUSTOMERNOTICE" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "BOOK"."CUSTOMERNOTICE" MODIFY ("TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTICE
--------------------------------------------------------

  ALTER TABLE "BOOK"."NOTICE" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "BOOK"."NOTICE" MODIFY ("TITLE" NOT NULL ENABLE);


--------------------------------------------------------
--  DDL for Sequence BNO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOOK"."BNO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CART_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOOK"."CART_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 161 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CUS_ORDER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOOK"."CUS_ORDER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EBOOK_REQNO
--------------------------------------------------------

   CREATE SEQUENCE  "BOOK"."EBOOK_REQNO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORDERNUMBER
--------------------------------------------------------

   CREATE SEQUENCE  "BOOK"."ORDERNUMBER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORGNO
--------------------------------------------------------

   CREATE SEQUENCE  "BOOK"."ORGNO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REPLY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOOK"."REPLY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REQNO
--------------------------------------------------------

   CREATE SEQUENCE  "BOOK"."REQNO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence RNO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOOK"."RNO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SALENUMBER
--------------------------------------------------------

   CREATE SEQUENCE  "BOOK"."SALENUMBER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 181 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ADMINNOTICE
--------------------------------------------------------

   CREATE SEQUENCE  "BOOK"."SEQ_ADMINNOTICE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BOOK
--------------------------------------------------------

   CREATE SEQUENCE  "BOOK"."SEQ_BOOK"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3101 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CUSTOMERNOTICE
--------------------------------------------------------

   CREATE SEQUENCE  "BOOK"."SEQ_CUSTOMERNOTICE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_DELIVERY
--------------------------------------------------------

   CREATE SEQUENCE  "BOOK"."SEQ_DELIVERY"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_EMPNO_BRONZE
--------------------------------------------------------

   CREATE SEQUENCE  "BOOK"."SEQ_EMPNO_BRONZE"  MINVALUE 1 MAXVALUE 6000 INCREMENT BY 1 START WITH 3040 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_EMPNO_DIAMOND
--------------------------------------------------------

   CREATE SEQUENCE  "BOOK"."SEQ_EMPNO_DIAMOND"  MINVALUE 1 MAXVALUE 999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_EMPNO_GOLD
--------------------------------------------------------

   CREATE SEQUENCE  "BOOK"."SEQ_EMPNO_GOLD"  MINVALUE 1 MAXVALUE 2999 INCREMENT BY 1 START WITH 2000 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_EMPNO_PLATINUM
--------------------------------------------------------

   CREATE SEQUENCE  "BOOK"."SEQ_EMPNO_PLATINUM"  MINVALUE 1 MAXVALUE 1999 INCREMENT BY 1 START WITH 1000 CACHE 20 NOORDER  NOCYCLE ;